# Generated by Django 3.0.4 on 2020-07-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
