# Generated by Django 3.0.4 on 2020-07-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_hobby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
