# Generated by Django 3.0.4 on 2020-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200419_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
    ]
